datasets:
  scifact:
    query_instruction: "Represent this sentence for searching relevant passages:"
    document_instruction: Null
  trec-covid-beir:
    query_instruction: "Represent this sentence for searching relevant passages:"
    document_instruction: Null
  fiqa:
    query_instruction: "Represent this sentence for searching relevant passages:"
    document_instruction: Null
  quora:
    query_instruction: "Represent this sentence for searching relevant passages:"
    document_instruction: Null
  nfcorpus:
    query_instruction: "Represent this sentence for searching relevant passages:"
    document_instruction: Null
  scidocs:
    query_instruction: "Represent this sentence for searching relevant passages:"
    document_instruction: Null
  webis-touche2020:
    query_instruction: "Represent this sentence for searching relevant passages:"
    document_instruction: Null
model:
  type: onnx
  batch_size: 32
  name_or_path: models/model-fp16.onnx
  tokenizer_name_or_path: models/sentence-transformers/model.sentence_transformer
  matryoshka_dim: Null  # Null if you don't want to use matryoshka dimension, otherwise select integer value
  score_function: cos_sim
  sep: ' ' # Seperator between different fields of the documents in corpus eg title, text, etc.
  cls: False  # Set to True if you want to use CLS token for scoring, otherwise set to False
mlflow:
  tracking_uri: https://rnd-mlflow.literatumonline.com/
  experiment_name: beir-evaluation
  run_name: bge-base-matryoshka-full-instruction
