datasets:
  scifact:
    query_instruction: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery:"
    document_instruction: Null
  trec-covid-beir:
    query_instruction: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery:"
    document_instruction: Null
  fiqa:
    query_instruction: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery:"
    document_instruction: Null
  quora:
    query_instruction: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery:"
    document_instruction: Null
  nfcorpus:
    query_instruction: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery:"
    document_instruction: Null
  scidocs:
    query_instruction: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery:"
    document_instruction: Null
  webis-touche2020:
    query_instruction: "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery:"
    document_instruction: Null
model:
  type: sentence_transformers
  batch_size: 4
  name_or_path: Qwen/Qwen3-Embedding-0.6B
  tokenizer_name_or_path: Qwen/Qwen3-Embedding-0.6B
  matryoshka_dim: Null  # Null if you don't want to use matryoshka dimension, otherwise select integer value
  score_function: cos_sim
  sep: ' ' # Seperator between different fields of the documents in corpus eg title, text, etc.
  model_kwargs:
    attention_implementation: flash_attention_2  # Use 'flash_attention_2' for better performance
    device_map: auto  # Automatically set device map for distributed inference
  tokenizer_kwargs:
    padding_side: left  # Padding side left for decoder architectures
mlflow:
  tracking_uri: https://rnd-mlflow.literatumonline.com/
  experiment_name: beir-evaluation
  run_name: qwen3-0.6b-matryoshka-full-instruction
