datasets:
  - scifact
  - trec-covid-beir
  - fiqa
  - quora
  - nfcorpus
  - scidocs
  - webis-touche2020
datasets_path: datasets
batch_size: 32
onnx_filename: bge_small_fp16_optimized.onnx
model_path: onnx_models
score_function: cos_sim
mlflow:
  tracking_uri: "https://mlflow-demo.atypon.com/"
  experiment_name: 'beir-faiss-bge-small'
bge:
  enable_query_instruction: True
  query_instruction: "Represent this sentence for searching relevant passages:"
  cls: True