datasets:
  - scifact
  - trec-covid-beir
  - fiqa
  - quora
  - nfcorpus
  - scidocs
  - webis-touche2020
datasets_path: datasets
batch_size: 32
onnx_filename: model-fp16.onnx
model_path: models/bge-base
matryoshka_dim: Null                                # Null if you don't want to use matryoshka dimension
score_function: cos_sim
mlflow:
  tracking_uri: "https://mlflow-demo.atypon.com/"
  experiment_name: 'beir-evaluation'
  run_name: 'bge-base-matryoshka-full-instruction'
bge:
  enable_query_instruction: True
  query_instruction: "Represent this sentence for searching relevant passages:"
  cls: False