datasets:
  - scifact
  - trec-covid-beir
  - fiqa
  - quora
  - nfcorpus
  - scidocs
  - webis-touche2020
batch_size: 16
onnx_filename: model-fp16.onnx
model_path: model/bge-small-matryoshka
matryoshka_dim: Null                                # Null if you don't want to use matryoshka dimension
score_function: cos_sim
mlflow:
  tracking_uri: "https://mlflow-demo.atypon.com/"
  experiment_name: 'beir-bge-small-matryoshka'
